### ISSUE TITLE
script crashes if given ID is wrong or account is disabled

### ISSUE THREAD

**Issue by naeem8642** [Snbig/InstaTrack#19]
C:\Users\cyb3r>python InstaTracker.py -i 7334396907
Traceback (most recent call last):
  File "C:\Users\cyb3r\InstaTracker.py", line 130, in <module>
    main()
  File "C:\Users\cyb3r\InstaTracker.py", line 113, in main
    username = useridToUsername(args.id)
  File "C:\Users\cyb3r\InstaTracker.py", line 59, in useridToUsername
    if json.loads(r).get("status") != 'ok':
  File "C:\Users\cyb3r\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\cyb3r\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\cyb3r\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Snbig** [comment]
Fixed.
Thanks to @sergioccrr
