### ISSUE TITLE
Error when using FindUserID

### ISSUE THREAD

**Issue by duttaditya18** [Snbig/InstaTrack#9]
Running `$ python3 InstaTracker.py -i <19 character UserID>`  gives the error:

```
Traceback (most recent call last):
  File "E:\Instaloader\InstaTracker.py", line 138, in <module>
    main()
  File "E:\Instaloader\InstaTracker.py", line 121, in main
    username = useridToUsername(args.id)
  File "E:\Instaloader\InstaTracker.py", line 58, in useridToUsername
    checkTokens()
  File "E:\Instaloader\InstaTracker.py", line 18, in checkTokens
    getTokens()
  File "E:\Instaloader\InstaTracker.py", line 28, in getTokens
    query_hash = re.findall(r'{value:!0}\);var s=\"(.*?)\"', r)[0]
IndexError: list index out of range
```

I am running the program on Python3.8.

I am really sorry if I am doing something really stupid. I am not at all comfortabe with Python

**Comment by darylkell** [comment]
See https://github.com/Snbig/InstaTrack/commit/43d83c77130a24ee9e59c59736ce98b49aaaa7ec#r36071017
